### PR TITLE
KSF-57: Move http://127.0.0.1:9080/sandbox to http://127.0.0.1:9080

### PR DESCRIPTION
**Pull request by vasner**
Add support for http://127.0.0.1:9080/ together with the old variant.

Review: @vadimol

### CODE REVIEW

**Review by vadimol — APPROVED** [review]
LGTM, but someone else must approve

**Review by Slash32 — COMMENTED** [review]
Looks good to me, but someone else should check.

**Comment by ikulikov** [comment]
LGTM

**Review by Slash32 — APPROVED** [review]

**Pull request merged**
